/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Workouts {
  created_time: string | null;
  exercise: string;
  notes: string | null;
  reps: number;
  user_id: number | null;
  weight: number;
  weight_type: string;
}

export interface DB {
  workouts: Workouts;
}
